name: Sincronizzazione Automatica Hevy Garmin

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Cambia instradamento di rete (Bypass 429)
        run: |
          sudo echo "nameserver 1.1.1.1" | sudo tee /etc/resolvconf/resolv.conf.d/base > /dev/null || true
          sudo echo "nameserver 8.8.8.8" | sudo tee -a /etc/resolvconf/resolv.conf.d/base > /dev/null || true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installa il programma
        run: pip install hevy2garmin

      - name: Avvia Sincronizzazione Standard
        env:
          HEVY_API_KEY: ${{ secrets.HEVY_API_KEY }}
          GARMIN_EMAIL: ${{ secrets.GARMIN_EMAIL }}
          GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
        run: hevy2garmin sync
