name: Sincronizzazione Automatica Hevy Garmin

on:
  schedule:
    - cron: '0 * * * *' # Gira ogni ora automaticamente
  workflow_dispatch: # Permette il lancio manuale

jobs:
  run-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installa il programma
        run: pip install hevy2garmin

      - name: Configura il Token del Browser
        run: |
          # Creiamo la cartella corretta dove lo script si aspetta di trovare i token salvati
          mkdir -p ~/.config/hevy2garmin/garmin_tokens
          # Prendiamo il Secret di GitHub e lo salviamo nel file di sessione richiesto
          echo '${{ secrets.GARMIN_TOKENS }}' > ~/.config/hevy2garmin/garmin_tokens/garmin_tokens.json

      - name: Avvia Sincronizzazione con Token
        env:
          HEVY_API_KEY: ${{ secrets.HEVY_API_KEY }}
          GARMIN_EMAIL: ${{ secrets.GARMIN_EMAIL }}
        run: hevy2garmin sync
